# wpa_supplicant configuration for SpacemiT K1
ctrl_interface=/data/vendor/wifi/wpa/sockets
update_config=1
device_name=BananaPi_F3
manufacturer=Sinovoip
model_name=BananaPi F3
model_number=F3
serial_number=0
device_type=10-0050F204-5
config_methods=physical_display virtual_push_button
p2p_disabled=1
external_sim=0
